spring:
  jpa:
    # 전송 쿼리 확인
    # show-sql, format_sql 옵션
    # 애플리케이션 실행 과정에 데이터베이스에 쿼리할 일이 있으면 실행 구문을 모두 보여주는 옵션
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 애플리케이션 실행 시 테이블을 생성하고 data.sql파일에 있는 뭐리를 실행하도록 하는 옵션
    defer-datasource-initialization: true

  # 실제 데이터를 확인하기 위한 H2 콘솔 활성화
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true